[sql]
driver = "mysql"
leader = "root:123456@tcp(127.0.0.1:3306)/suna_example"
log = true

[redis]
mode = "singleton"
nodes = ["redis://127.0.0.1:6379"]

[session]
cookie = "xsk"
header = "X-Suna-Session"

[session.captcha]
skip-in-debug = true

[secret]
key = "file://./.secret"  # will load the file: "./.secret"

[auth]
header = "X-Auth-Token"
cookie = "alk"
